= Разработка протокола самоописания устройств IoT в самоорганизующихся mesh-сетях коллективного пользования на личных приусадебных хозяйствах

Технологии IoT могут решать весьма значимые задачи в масштабах личных приусадебных хозяйств по мониторингу и управлению устройствами ("умные теплицы", "автополив" и т.п.). Однако, применение таких технологий имеет достаточно высокий порог входа включая требования к инфраструктуре (наличие каналов связи) и техническую компетентность. 
В настоящей работе рассматривается возможность создания класса самоописываемых устройств (контроллеров), которые способны самостоятельно организовывать mesh-сети для создания канала связи с пользовательским устройством, а также конфигурировать "под себя" интерфейс управления на пользовательском устройстве. 

Ключевым компонентом для данного сценария является манифест конечного устройства (контроллера), который бы содержал достаточную для решения указанной задачи информацию. В работе обоснованы ключевые требования к манифесту и способы их реализации: 

* идентифицируемость - подписанный глобальный идентификатор;
* вариативность сценариев функционирования - характеристики для определения оптимальной роли в mesh-сети;
* универсальность и выразительность - определение функциональных характеристик устройства как конечного автомата.

Известные структуры протоколов определяют интерфейсы (WoT TD) или параметров (патент USPTO), но внутреннюю логику поведения на основе переходов между состояниями. *Новизна предложенного подхода* состоит в прямом формализованном описании исполнительного устройства как конечного автомата внутри манифеста. 

**Ключевая семантика манифеста (в нотации BNF)**
```text
<manifest> ::= <manifest-version> <message-envelope> <device-identity> 
               <network-integration> <functional-description> 

<functional-description> ::= "{" "device_type:" <device-type>
                              <optional-sensors>
                              <optional-actuators>
                              <optional-relationships> "}"

<actuator> ::= "{" "id:" <string> "type:" <actuator-type> 
                "state_machine:" <state-machine> 
                <optional-initial-state>
                "commands:" <command-list> "}"

<state-machine> ::= "{" "states:" <state-def-list> 
                     "transitions:" <transition-list> "}"
```

В рамках настоящей работы реализована полная "plug-and-work" цепочка синхронного взаимодействия платформы "IoT-greenhouse" "контроллер - платформа IoT - веб-интерфейс", которая работает в режиме опытной эксплуатации с реальными устройствами. Развитие проекта предполагает полную реализацию механизма самоописания устройств с автоматической интеграцией в mesh-сеть общего пользования на основе расширений протокола WoT 3.0.

Использованные источники:

W3C Web of Things (WoT) Thing Description 1.1 : W3C Recommendation 19 January 2023 / S. Kaebisch, T. Kamiya, M. McCool, V. Charpenay ; World Wide Web Consortium. – URL: https://www.w3.org/TR/wot-thing-description/ (дата обращения: 15.03.2025). – Текст : электронный.

IETF RFC 9124 A Manifest Information Model for Firmware Updates in Internet of Things (IoT) Devices / B. Moran, H. Tschofenig, H. Birkholz ; Internet Engineering Task Force. – January 2022. – URL: https://datatracker.ietf.org/doc/html/rfc9124 (дата обращения: 15.03.2025). – Текст : электронный.

IETF RFC 9019 A Firmware Update Architecture for Internet of Things / B. Moran, H. Tschofenig, H. Birkholz ; Internet Engineering Task Force. – April 2021. – URL: https://datatracker.ietf.org/doc/html/rfc9019 (дата обращения: 15.03.2025). – Текст : электронный.